module Briefly
  # An ordered list of facade-wide and global `rescue_from` registrations, queried at dispatch time.
  class RescueRegistry
    # A single registration.
    class Entry < ::Struct[untyped]
      attr_accessor klass: Class
      attr_accessor handler: Briefly::handler

      def self.new: (Class klass, Briefly::handler handler) -> Entry
    end

    @entries: Array[Entry]
    @mutex: Thread::Mutex

    def initialize: () -> void
    def add: (Class klass, Briefly::handler handler) -> self
    def handler_for: (Exception error) -> Briefly::handler?
    def size: () -> Integer
    def clear: () -> self
  end
end
